---
- name: Setup control node
  hosts: control
  vars:
    USER: rhel
  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: "0755"
      loop:
        - /home/{{ USER }}/ansible
        - /home/{{ USER }}/ansible-files
        - /home/{{ USER }}/ansible-files/.logs

    - name: Create ansible.cfg
      ansible.builtin.copy:
        content: |
          [defaults]
          inventory = /home/{{ USER }}/ansible-files/inventory
          host_key_checking = False
        dest: /home/{{ USER }}/.ansible.cfg
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: "0644"

    - name: Create .gitconfig
      ansible.builtin.copy:
        content: |
          [user]
            email = "{{ USER }}@example.com"
            name = Red Hat
        dest: /home/{{ USER }}/.gitconfig
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: "0664"

    - name: Create ansible-navigator.yml
      ansible.builtin.copy:
        content: |
          ---
          ansible-navigator:
            ansible:
              inventory:
                entries:
                - /home/{{ USER }}/ansible-files/inventory
            execution-environment:
              container-engine: podman
              enabled: true
              image: quay.io/acme_corp/servicenow-ee:latest
              pull:
                policy: missing
              environment-variables:
                pass:
                  - CONTROLLER_USERNAME
                  - CONTROLLER_PASSWORD
                  - CONTROLLER_VERIFY_SSL
                set:
                  CONTROLLER_HOST: control.${_SANDBOX_ID}.svc.cluster.local
            logging:
              level: debug
            mode: stdout
            playbook-artifact:
              save-as: /home/{{ USER }}/.logs/{playbook_name}-artifact-{time_stamp}.json
        dest: "{{ item }}"
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: "0644"
      loop:
        - /home/{{ USER }}/ansible-navigator.yml
        - /home/{{ USER }}/.ansible-navigator.yml
        - /home/{{ USER }}/ansible-files/ansible-navigator.yml

    - name: Set controller access env vars for system
      become: true
      ansible.builtin.blockinfile:
        path: /etc/environment
        insertafter: 'EOF'
        block: |
          CONTROLLER_HOST=localhost
          CONTROLLER_USERNAME=admin
          CONTROLLER_PASSWORD='ansible123!'
          CONTROLLER_VERIFY_SSL=false

    - name: Install packages
      become: true
      ansible.builtin.dnf:
        name:
          - nc
          # - ansible-navigator
          # - ansible-lint
        state: present

- name: Setup nodes
  hosts: node1,node2,node3
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: cups-filesystem
        state: present
