---

antora:
  name: modules
  dir: www
  modules:
    - name: module_1
      label: Module 1
    - name: module-02
      label: Module 2
tabs:
  - name: terminal
    port: 443
    path: /tty1
  - name: Editor
    port: 443
    path: /codeserver/
  - name: Myweb
    url: https://www.redhat.com