---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Module 1
    - name: 02-agenda
      label: Module 2
    - name: 03-introduction
      label: Module 3
    - name: 04-solution-1
      label: Module 4
    - name: 05-solution-2
      label: Module 5
    - name: 06-solution-3
      label: Module 6

tabs:
  - name: editor
    port: 443
    path: /codeserver/?folder=/home/coder/workplace
  - name: terminal
    port: 443
    path: /tty1
  - name: VScode
    port: 8443
    path: /?folder=/home/coder/workplace

  