---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Module 1
    - name: 02-agenda
      label: Module 2
tabs:
  - name: terminal
    port: 443
    path: /tty1
  - name: editor
    port: 443
    path: /codeserver/