---
- name: Demo Playbook for the ansible-runner API
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Check if module_dir is defined
      ansible.builtin.fail:
        msg: "module_dir not defined"
      when: module_dir is not defined

    - name: Check if module_stage is defined
      ansible.builtin.fail:
        msg: "module_stage not defined"
      when: module_stage is not defined

    - name: Check if module_dir and module_stage exists
      ansible.builtin.stat:
        path: ./{{ module_dir }}/{{ item }}/{{ module_stage }}.sh
      register: r_script
      loop: "{{ groups['all'] }}"

- name: Run on control node
  hosts: control
  gather_facts: false
  become: true
  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: tasks.yml
      when:
        - item.stat.exists
        - item.item == 'control'
      loop: "{{ hostvars.localhost.r_script.results }}"

- name: Run on node1
  hosts: node1
  gather_facts: false
  become: true
  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: tasks.yml
      when:
        - item.stat.exists
        - item.item == 'node1'
      loop: "{{ hostvars.localhost.r_script.results }}"

- name: Run on node2
  hosts: node2
  gather_facts: false
  become: true
  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: tasks.yml
      when:
        - item.stat.exists
        - item.item == 'node2'
      loop: "{{ hostvars.localhost.r_script.results }}"

- name: Run on node3
  hosts: node3
  gather_facts: false
  become: true
  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: tasks.yml
      when:
        - item.stat.exists
        - item.item == 'node3'
      loop: "{{ hostvars.localhost.r_script.results }}"
