---
- name: Solve control node
  hosts: controller
  gather_facts: false
  vars:
    USER: rhel
  tasks:
    - name: Create hosts
      ansible.builtin.copy:
        content: |
          [web]
          node1
          node2
        dest: /home/{{ USER }}/ansible-files/hosts
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: "0644"
