---
- name: Solve control node
  hosts: controller
  vars:
    USER: rhel
  tasks:
    - name: Get stats of system_setup.yml file
      ansible.builtin.stat:
        path: /home/{{ USER }}/ansible-files/system_setup.yml
      register: r_system

    - name: Fail if the host file does not exist
      ansible.builtin.fail:
        msg: "system file doesn't exist"
      when: not r_system.stat.exists
