- name: Basic System Setup
  hosts: web
  become: true
  gather_facts: false
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: rpm

    - name: Check whether a package called foobar is installed
      ansible.builtin.fail:
        msg: "httpd is not installed"
      when: "'httpd' not in ansible_facts.packages"
