---
- name: Solve control node
  hosts: controller
  vars:
    USER: rhel
  tasks:
    - name: Create system-setup.yml
      ansible.builtin.copy:
        content: |
          ---
          - name: Basic System Setup
            hosts: node1
            become: true
            tasks:
              - name: Install security updates for the kernel
                ansible.builtin.dnf:
                  name: 'kernel'
                  state: latest
                  security: true

              - name: Create a new user
                ansible.builtin.user:
                  name: myuser
                  state: present
                  create_home: true
        dest: /home/{{ USER }}/ansible-files/system_setup.yml
        owner: "{{ USER }}"
        group: "{{ USER }}"
        mode: "0644"

- name: Setup nodes
  hosts: nodes
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: cups-filesystem
        state: present

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
