- name: Basic System Setup
  hosts: node1
  become: true
  tasks:

    - name: Check user existence
      ansible.builtin.command:
        cmd: id myuser
      ignore_errors: true
      register: user_check

    - name: Report user status
      ansible.builtin.debug:
        msg: "User 'myuser' exists."
      when: user_check.rc == 0
