- name: Solve control node
  hosts: controller
  gather_facts: false
  vars:
    USER: rhel
  tasks:
    - name: Get stats of motd.j2 file
      ansible.builtin.stat:
        path: /home/{{ USER }}/ansible-files/templates/motd.j2
      register: r_system

    - name: Write fail logs
      ansible.builtin.copy:
        content: "Challenge 1.8 - The motd.j2 file does not exist in the specified directory."
        dest: "{{ job_info_dir }}/output.txt"
        mode: "0644"
      when: not r_system.stat.exists
      delegate_to: localhost

    - name: Fail if the host file does not exist
      ansible.builtin.fail:
        msg: "motd file doesn't exist"
      when: not r_system.stat.exists
